// Bundles and minifies every browser script in src/client/*.ts with rolldown and
// writes each one to src/client/gen/<name>.ts as `export default "<code>"`, so
// templates.ts imports plain strings and neither wrangler, tsc nor vitest needs a
// loader rule. Runs before dev, deploy, typecheck and test (see package.json).

import { mkdir, readdir, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { rolldown } from "rolldown";

const srcDir = new URL("../src/client/", import.meta.url);
const outDir = new URL("gen/", srcDir);
await mkdir(outDir, { recursive: true });

const entries = (await readdir(srcDir)).filter((f) => f.endsWith(".ts"));
for (const file of entries) {
  const bundle = await rolldown({
    input: fileURLToPath(new URL(file, srcDir)),
    platform: "browser",
    logLevel: "warn",
  });
  const { output } = await bundle.generate({ format: "iife", minify: true });
  await bundle.close();
  const code = output[0].code.trim();
  if (code.includes("</script")) throw new Error(`${file}: bundle contains "</script", which would break inlining`);
  const name = file.replace(/\.ts$/, "");
  const module = `// Generated by scripts/build-client.mjs from src/client/${file} — do not edit.\nexport default ${JSON.stringify(code)};\n`;
  await writeFile(new URL(`${name}.ts`, outDir), module);
  console.log(`client: ${file} → gen/${name}.ts (${code.length} bytes)`);
}
